### ISSUE TITLE
Add an option to check from list of subdomains

### ISSUE THREAD

**Issue by deathflash1411** [Goon-Security/Rupert#1]
So I use multiple tools to prepare a list of subdomains (amass, assetfinder, subfinder).
Add the functionality to directly check for subdomain takeovers from a given list of subdomains, this option must run subfinder to enumerate subdomains it should directly check for takeovers from the given list of subdomains.

**Comment by jaggarhenry** [comment]
We can add reading subdomains from file and skip the subfinder step for sure.
Could be interesting to be able to pipe into Rupert like you see with HTTProbe, as well.

Donald will add the read from file option tonight.

**Comment by jaggarhenry** [comment]
@deathflash1411 Updated with `-sf [FILE]` flag.
